name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r week7/day2/requirements.txt

      - name: Run Ruff
        run: |
          ruff check week7/day2

      - name: Run Tests
        run: |
          pytest week7/day2/test/test.py -v