"""created and removed ownerid

Revision ID: 25a51a260021
Revises: 1255f24e3092
Create Date: 2026-04-28 12:35:26.513179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a51a260021'
down_revision: Union[str, Sequence[str], None] = '1255f24e3092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_user'), 'categories', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
